/eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
---
spring:
  profiles: primary
  application:
    name: lab-4-eureka-server   
server:
  port: 8011/eureka/  
eureka:
  instance:
    hostname: eureka-primary       
  client:
    registerWithEureka: true
    fetchRegistry: true        
    serviceUrl:
      defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/

---
spring:
  profiles: secondary
  application:
    name: lab-4-eureka-server      
server:
  port: 8012/eureka/
eureka:
  instance:
    hostname: eureka-secondary       
  client:
    registerWithEureka: true
    fetchRegistry: true        
    serviceUrl:
      defaultZone: http://eureka-tertiary:8013/eureka/,http://eureka-primary:8011/eureka/

---
spring:
  profiles: tertiary
  application:
    name: lab-4-eureka-server      
server:
  port: 8013/eureka/
eureka:
  instance:
    hostname: eureka-tertiary       
  client:
    registerWithEureka: true
    fetchRegistry: true    
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/  
---
spring:
  profiles: subject
words: aaa,bbb,ccc,ddd

---
spring:
  profiles: verb
words: aaa,bbb,ccc,ddd

---
spring:
  profiles: article
words: aaa,bbb,ccc,ddd

---
spring:
  profiles: adjective
words: aaa,bbb,ccc,ddd

---
spring:
  profiles: noun
words: aaa,bbb,ccc,ddd
